Project-Condor:
  org: ss14-art
  project: 2
  inbox: Inbox
  labels:
    "W: В прогрессе": "В прогрессе"
    "W: Обсуждается": "Обсуждается"
    "W: Невыполненные": "Невыполненные"
    "W: Следующее": "Следующее"
