using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.SmartFridge;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SmartFridge;

// open-space edit start
public sealed record SmartFridgeListData(EntityUid Representative, SmartFridgeEntry Entry, int Amount);
// open-space edit end

[GenerateTypedNameReferences]
public sealed partial class SmartFridgeMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    // open-space edit start
    public event Action<SmartFridgeListData>? OnDispenseOne;
    public event Action<SmartFridgeListData, int>? OnDispenseAmount;
    public event Action<SmartFridgeListData>? OnDispenseAll;
    // open-space edit end

    public SmartFridgeMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    // open-space edit start
    public void Populate(Entity<SmartFridgeComponent> ent)
    {
        EntriesContainer.RemoveAllChildren();
        var listData = new List<SmartFridgeListData>();

        foreach (var item in ent.Comp.Entries)
        {
            if (!ent.Comp.ContainedEntries.TryGetValue(item, out var items) || items.Count == 0)
                continue;

            var representative = _entityManager.GetEntity(items.First());
            listData.Add(new SmartFridgeListData(representative, item, items.Count));
        }

        EmptyLabel.Visible = listData.Count == 0;

        foreach (var entry in listData.OrderBy(static x => x.Entry.Name, StringComparer.CurrentCulture))
        {
            var item = new SmartFridgeItem(entry.Representative, entry.Entry.Name, entry.Amount);
            item.OnDispenseOne += () => OnDispenseOne?.Invoke(entry);
            item.OnDispenseAmount += amount => OnDispenseAmount?.Invoke(entry, amount);
            item.OnDispenseAll += () => OnDispenseAll?.Invoke(entry);
            EntriesContainer.AddChild(item);
        }
    }
    // open-space edit end

    public void SetFlavorText(string flavor)
    {
        LeftFlavorLabel.Text = flavor;
    }

    // open-space edit start
    public void SetWindowTitle(string title)
    {
        Title = title;
    }

    public void SetAccessState(bool showBanner, string text)
    {
        AuthorizationBanner.Visible = showBanner;
        AuthorizationBannerLabel.Text = text;
    }
    // open-space edit end
}
