using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SmartFridge;

[GenerateTypedNameReferences]
public sealed partial class SmartFridgeItem : PanelContainer
{
    // open-space edit start
    public event Action? OnDispenseOne;
    public event Action<int>? OnDispenseAmount;
    public event Action? OnDispenseAll;
    // open-space edit end

    public SmartFridgeItem(EntityUid uid, string text, int amount)
    {
        RobustXamlLoader.Load(this);

        // open-space edit start
        if (uid.IsValid())
            EntityView.SetEntity(uid);
        else
            EntityView.Visible = false;
        // open-space edit end

        NameLabel.Text = text;

        // open-space edit start
        CountLabel.Text = Loc.GetString("smart-fridge-component-stock", ("amount", amount));
        AmountLineEdit.Text = Math.Max(1, amount).ToString();

        DispenseOneButton.OnPressed += _ => OnDispenseOne?.Invoke();
        DispenseAllButton.OnPressed += _ => OnDispenseAll?.Invoke();
        AmountLineEdit.OnTextEntered += args =>
        {
            if (TryParseRequestedAmount(args.Text, out var requestedAmount))
            {
                OnDispenseAmount?.Invoke(requestedAmount);
            }
        };
        // open-space edit end
    }

    // open-space edit start
    private bool TryParseRequestedAmount(string text, out int amount)
    {
        amount = 0;
        if (!int.TryParse(text, out var parsed) || parsed <= 0)
            return false;

        amount = parsed;
        AmountLineEdit.Text = parsed.ToString();
        return true;
    }
    // open-space edit end
}
