using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Numerics;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Chemistry.UI;

[GenerateTypedNameReferences]
public sealed partial class ChemMasterWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly SpriteSystem _sprite;

    public event Action<ReagentId, ChemMasterReagentAmount, bool>? OnReagentAmountPressed;
    public event Action<ReagentId, FixedPoint2, bool>? OnCustomAmountPressed;
    public event Action<ReagentId>? OnAnalyzePressed;
    // open-space edit start
    public event Action<ChemMasterMode>? OnBufferModeChanged;
    // open-space edit end

    public readonly Button[] PillTypeButtons;

    private const string PillsRsiPath = "/Textures/Objects/Specific/Chemistry/pills.rsi";

    public string PillLabelLine => PillLabelLineEdit.Text;

    public ChemMasterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entityManager.System<SpriteSystem>();

        PillTypeButtons = BuildSpriteButtonGrid(PillGrid, SharedChemMaster.PillTypes, PillsRsiPath, i => $"pill{i + 1}", 10);

        PillDosage.InitDefaultButtons();

        PillLabelLineEdit.IsValid = text => text.Length <= SharedChemMaster.LabelMaxLength;

        // open-space edit start
        BufferDiscardCheckBox.OnToggled += args =>
            OnBufferModeChanged?.Invoke(args.Pressed ? ChemMasterMode.Discard : ChemMasterMode.Transfer);
        // open-space edit end
    }

    public void UpdateState(ChemMasterBoundUserInterfaceState state)
    {
        // open-space edit start
        var bufferActionsEnabled = state.Mode == ChemMasterMode.Discard || state.InputContainerInfo is not null;
        // open-space edit end
        BuildContainerPanel(InputContainerInfo, state.InputContainerInfo, false, true);
        BuildBufferPanel(state.BufferReagents, bufferActionsEnabled);
        BuildCustomizationPanel(state.OutputContainerInfo);

        if (state.SelectedPillType < PillTypeButtons.Length)
            PillTypeButtons[state.SelectedPillType].Pressed = true;

        UpdateDosageFields(state);

        InputEjectButton.Disabled = state.InputContainerInfo is null;
        // open-space edit start
        BufferDiscardCheckBox.Pressed = state.Mode == ChemMasterMode.Discard;
        // open-space edit end
        OutputEjectButton.Disabled = state.OutputContainerInfo is null;
        CreatePillButton.Disabled = state.BufferCurrentVolume == 0;
    }

    private void UpdateDosageFields(ChemMasterBoundUserInterfaceState state)
    {
        var bufferVolume = state.BufferCurrentVolume?.Int() ?? 0;
        var pillMax = Math.Max(1, Math.Min(bufferVolume, (int) state.PillDosageLimit));

        PillDosage.IsValid = value => value > 0 && value <= pillMax;

        if (PillDosage.Value <= 0 || PillDosage.Value > pillMax)
            PillDosage.Value = pillMax;
    }

    private Button[] BuildSpriteButtonGrid(GridContainer grid, uint count, string rsiPath, Func<uint, string> stateSelector, int columns)
    {
        var group = new ButtonGroup();
        var buttons = new Button[count];

        for (uint i = 0; i < count; i++)
        {
            var button = new Button
            {
                Access = AccessLevel.Public,
                Group = group,
                MaxSize = new Vector2(42, 28)
            };

            var column = i % columns;
            if (column == 0)
                button.StyleClasses.Add(StyleClass.ButtonOpenRight);
            else if (column == columns - 1)
                button.StyleClasses.Add(StyleClass.ButtonOpenLeft);
            else
                button.StyleClasses.Add(StyleClass.ButtonOpenBoth);

            var specifier = new SpriteSpecifier.Rsi(new ResPath(rsiPath), stateSelector(i));
            button.AddChild(new TextureRect
            {
                Texture = _sprite.Frame0(specifier),
                TextureScale = new Vector2(1.5f, 1.5f),
                Stretch = TextureRect.StretchMode.KeepCentered
            });

            grid.AddChild(button);
            buttons[i] = button;
        }

        return buttons;
    }

    // open-space edit start
    private void BuildContainerPanel(Control container, ContainerInfo? info, bool fromBuffer, bool amountButtonsEnabled)
    // open-space edit end
    {
        container.Children.Clear();

        if (info is null)
        {
            container.Children.Add(new Label
            {
                Text = Loc.GetString("chem-master-window-no-container-loaded-text")
            });
            return;
        }

        AddContainerHeader(container, info.DisplayName, info.CurrentVolume, info.MaxVolume);

        if (info.Reagents == null || info.Reagents.Count == 0)
        {
            container.Children.Add(new Label
            {
                Text = Loc.GetString("chem-master-window-container-empty-text")
            });
            return;
        }

        foreach (var reagent in info.Reagents)
        {
            container.Children.Add(BuildReagentRow(reagent.Reagent, reagent.Quantity, fromBuffer, amountButtonsEnabled));
        }
    }

    // open-space edit start
    private void BuildBufferPanel(IReadOnlyList<ReagentQuantity> bufferReagents, bool amountButtonsEnabled)
    // open-space edit end
    {
        BufferInfo.Children.Clear();

        if (bufferReagents.Count == 0)
        {
            BufferInfo.Children.Add(new Label
            {
                Text = Loc.GetString("chem-master-window-buffer-empty-text")
            });
            return;
        }

        foreach (var reagent in bufferReagents)
        {
            BufferInfo.Children.Add(BuildReagentRow(reagent.Reagent, reagent.Quantity, true, amountButtonsEnabled));
        }
    }

    private void BuildCustomizationPanel(ContainerInfo? info)
    {
        OutputContainerInfo.Children.Clear();

        if (info is null)
        {
            OutputContainerInfo.Children.Add(new Label
            {
                Text = Loc.GetString("chem-master-window-no-output-container-loaded-text")
            });
            return;
        }

        AddContainerHeader(OutputContainerInfo, info.DisplayName, info.CurrentVolume, info.MaxVolume);

        if (info.Entities != null)
        {
            foreach (var (name, quantity) in info.Entities)
            {
                OutputContainerInfo.Children.Add(new Label
                {
                    Text = Loc.GetString("chem-master-window-custom-container-item", ("name", name), ("quantity", quantity))
                });
            }
        }

        if (info.Reagents != null)
        {
            foreach (var reagent in info.Reagents)
            {
                var name = _prototypeManager.TryIndex(reagent.Reagent.Prototype, out ReagentPrototype? proto)
                    ? proto.LocalizedName
                    : reagent.Reagent.Prototype;

                OutputContainerInfo.Children.Add(new Label
                {
                    Text = Loc.GetString("chem-master-window-custom-container-reagent", ("name", name), ("quantity", reagent.Quantity))
                });
            }
        }
    }

    private void AddContainerHeader(Control container, string name, FixedPoint2 current, FixedPoint2 max)
    {
        container.Children.Add(new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Children =
            {
                new Label { Text = name },
                new Control { HorizontalExpand = true },
                new Label
                {
                    Text = Loc.GetString("chem-master-window-container-volume", ("current", current), ("max", max)),
                    StyleClasses = { StyleClass.LabelWeak }
                }
            }
        });
    }

    // open-space edit start
    private Control BuildReagentRow(ReagentId reagentId, FixedPoint2 quantity, bool fromBuffer, bool amountButtonsEnabled)
    // open-space edit end
    {
        var localizedName = _prototypeManager.TryIndex(reagentId.Prototype, out ReagentPrototype? proto)
            ? proto.LocalizedName
            : reagentId.Prototype;

        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        row.AddChild(new Label
        {
            Text = Loc.GetString("chem-master-window-reagent-row", ("quantity", quantity), ("reagent", localizedName)),
            HorizontalExpand = true
        });

        row.AddChild(MakeAnalyzeButton(reagentId));
        row.AddChild(MakeAmountButton("1", reagentId, ChemMasterReagentAmount.U1, fromBuffer, amountButtonsEnabled));
        row.AddChild(MakeAmountButton("5", reagentId, ChemMasterReagentAmount.U5, fromBuffer, amountButtonsEnabled));
        row.AddChild(MakeAmountButton("10", reagentId, ChemMasterReagentAmount.U10, fromBuffer, amountButtonsEnabled));
        row.AddChild(MakeAmountButton(Loc.GetString("chem-master-window-buffer-all-amount"), reagentId, ChemMasterReagentAmount.All, fromBuffer, amountButtonsEnabled));
        row.AddChild(MakeCustomAmountButton(reagentId, fromBuffer, amountButtonsEnabled));

        return row;
    }

    private Button MakeAnalyzeButton(ReagentId reagentId)
    {
        var button = new Button
        {
            Text = Loc.GetString("chem-master-window-analyze-button")
        };

        button.OnPressed += _ => OnAnalyzePressed?.Invoke(reagentId);
        return button;
    }

    // open-space edit start
    private Button MakeAmountButton(string text, ReagentId reagentId, ChemMasterReagentAmount amount, bool fromBuffer, bool enabled)
    // open-space edit end
    {
        var button = new Button
        {
            Text = text,
            // open-space edit start
            Disabled = !enabled
            // open-space edit end
        };

        button.OnPressed += _ => OnReagentAmountPressed?.Invoke(reagentId, amount, fromBuffer);
        return button;
    }

    // open-space edit start
    private Button MakeCustomAmountButton(ReagentId reagentId, bool fromBuffer, bool enabled)
    // open-space edit end
    {
        var button = new Button
        {
            Text = Loc.GetString("chem-master-window-custom-amount-button"),
            // open-space edit start
            Disabled = !enabled
            // open-space edit end
        };

        button.OnPressed += _ => OpenCustomAmountDialog(reagentId, fromBuffer);
        return button;
    }

    private void OpenCustomAmountDialog(ReagentId reagentId, bool fromBuffer)
    {
        var entry = new QuickDialogEntry(
            "amount",
            QuickDialogEntryType.Integer,
            Loc.GetString("chem-master-window-custom-amount-dialog-prompt"));
        var window = new DialogWindow(
            Loc.GetString("chem-master-window-custom-amount-dialog-title"),
            new List<QuickDialogEntry> { entry });

        window.OnConfirmed += values =>
        {
            if (!values.TryGetValue("amount", out var value) || !int.TryParse(value, out var amount) || amount <= 0)
                return;

            OnCustomAmountPressed?.Invoke(reagentId, FixedPoint2.New(amount), fromBuffer);
        };
    }
}
