using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Numerics;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Chemistry.UI;

/// <summary>
/// Client-side UI used to control a <see cref="ReagentDispenserComponent"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ReagentDispenserWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public event Action<ReagentId>? OnDispenseReagentButtonPressed;
    public event Action<ReagentId, ReagentDispenserContainerAction, FixedPoint2>? OnContainerActionPressed;

    // open-space edit start
    private readonly List<(ReagentId Reagent, Button Button)> _reagentButtons = new();
    private ReagentDispenserDispenseAmount _lastSelectedAmount;
    private List<ReagentDispenserInventoryItem>? _lastInventory;
    // open-space edit end

    public ReagentDispenserWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(ReagentDispenserBoundUserInterfaceState state)
    {
        AmountGrid.Selected = ((int) state.SelectedDispenseAmount).ToString();
        EnergyBar.MaxValue = state.MaxEnergy;
        EnergyBar.Value = state.CurrentEnergy;
        EnergyValue.Text = Loc.GetString(
            "reagent-dispenser-window-energy-value",
            ("current", (int) MathF.Floor(state.CurrentEnergy)),
            ("max", (int) state.MaxEnergy));

        UpdateReagentsList(state.Inventory, state.SelectedDispenseAmount, state.CurrentEnergy);
        UpdateContainerInfo(state.OutputContainer);

        EjectButton.Disabled = state.OutputContainer is null;
    }

    private void UpdateReagentsList(
        List<ReagentDispenserInventoryItem> inventory,
        ReagentDispenserDispenseAmount selectedAmount,
        float energy)
    {
        // open-space edit start
        if (!ShouldRebuildReagentList(inventory, selectedAmount))
        {
            UpdateReagentButtonAvailability(selectedAmount, energy);
            return;
        }

        ReagentList.Children.Clear();
        _reagentButtons.Clear();
        _lastInventory = new List<ReagentDispenserInventoryItem>(inventory);
        _lastSelectedAmount = selectedAmount;

        var selected = (int) selectedAmount;
        foreach (var item in inventory)
        {
            var colorPanel = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = item.ReagentColor },
                MinSize = new Vector2(20, 20)
            };

            var reagentButton = new Button
            {
                Text = item.ReagentLabel,
                Disabled = energy < selected
            };
            reagentButton.OnPressed += _ => OnDispenseReagentButtonPressed?.Invoke(item.ReagentId);
            _reagentButtons.Add((item.ReagentId, reagentButton));

            ReagentList.Children.Add(new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Children =
                {
                    colorPanel,
                    reagentButton
                }
            });
        }
        // open-space edit end
    }

    // open-space edit start
    private bool ShouldRebuildReagentList(
        IReadOnlyList<ReagentDispenserInventoryItem> inventory,
        ReagentDispenserDispenseAmount selectedAmount)
    {
        if (_lastInventory == null || selectedAmount != _lastSelectedAmount || inventory.Count != _lastInventory.Count)
            return true;

        for (var i = 0; i < inventory.Count; i++)
        {
            var current = inventory[i];
            var previous = _lastInventory[i];
            if (current.ReagentId != previous.ReagentId ||
                current.ReagentLabel != previous.ReagentLabel ||
                current.ReagentColor != previous.ReagentColor)
            {
                return true;
            }
        }

        return false;
    }

    private void UpdateReagentButtonAvailability(ReagentDispenserDispenseAmount selectedAmount, float energy)
    {
        var disabled = energy < (int) selectedAmount;
        foreach (var (_, button) in _reagentButtons)
        {
            button.Disabled = disabled;
        }
    }
    // open-space edit end

    private void UpdateContainerInfo(ContainerInfo? containerInfo)
    {
        ContainerInfo.Children.Clear();

        if (containerInfo is null)
        {
            ContainerInfoName.Text = Loc.GetString("reagent-dispenser-window-container-title");
            ContainerInfoFill.Text = string.Empty;
            ContainerInfo.Children.Add(new Label
            {
                Text = Loc.GetString("reagent-dispenser-window-no-container-loaded-text")
            });
            return;
        }

        ContainerInfoName.Text = containerInfo.DisplayName;
        ContainerInfoFill.Text = Loc.GetString(
            "reagent-dispenser-window-container-volume",
            ("current", containerInfo.CurrentVolume),
            ("max", containerInfo.MaxVolume));

        if (containerInfo.Reagents == null || containerInfo.Reagents.Count == 0)
        {
            ContainerInfo.Children.Add(new Label
            {
                Text = Loc.GetString("reagent-dispenser-window-container-empty-text")
            });
            return;
        }

        foreach (var (reagentId, quantity) in containerInfo.Reagents)
        {
            var localizedName = _prototypeManager.TryIndex(reagentId.Prototype, out ReagentPrototype? proto)
                ? proto.LocalizedName
                : reagentId.Prototype;

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true
            };

            row.AddChild(new Label
            {
                Text = Loc.GetString(
                    "reagent-dispenser-window-container-reagent",
                    ("quantity", quantity),
                    ("reagent", localizedName)),
                HorizontalExpand = true
            });

            row.AddChild(MakeActionButton(
                Loc.GetString("reagent-dispenser-window-analyze-button"),
                reagentId,
                ReagentDispenserContainerAction.Analyze));
            row.AddChild(MakeActionButton("1", reagentId, ReagentDispenserContainerAction.Spill, FixedPoint2.New(1)));
            row.AddChild(MakeActionButton("5", reagentId, ReagentDispenserContainerAction.Spill, FixedPoint2.New(5)));
            row.AddChild(MakeActionButton("10", reagentId, ReagentDispenserContainerAction.Spill, FixedPoint2.New(10)));
            row.AddChild(MakeActionButton(
                Loc.GetString("reagent-dispenser-window-spill-all-button"),
                reagentId,
                ReagentDispenserContainerAction.SpillAll,
                quantity));
            row.AddChild(MakeActionButton(
                Loc.GetString("reagent-dispenser-window-delete-button"),
                reagentId,
                ReagentDispenserContainerAction.Delete,
                quantity));

            ContainerInfo.Children.Add(row);
        }
    }

    private Button MakeActionButton(
        string text,
        ReagentId reagentId,
        ReagentDispenserContainerAction action,
        FixedPoint2 quantity = default,
        string? extraStyle = null)
    {
        var button = new Button
        {
            Text = text
        };

        if (extraStyle != null)
            button.StyleClasses.Add(extraStyle);

        button.OnPressed += _ => OnContainerActionPressed?.Invoke(reagentId, action, quantity);
        return button;
    }
}
