using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Chemistry.UI;

[GenerateTypedNameReferences]
public sealed partial class SolutionHeaterWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public event Action<float>? OnTargetTemperatureChanged;
    public event Action? OnToggleAutoEjectPressed;
    public event Action? OnToggleEnabledPressed;
    public event Action? OnEjectPressed;

    public SolutionHeaterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // open-space edit start
        TargetTemperatureLine.OnTextEntered += _ => SubmitTargetTemperature();
        TargetTemperatureLine.OnFocusExit += _ => SubmitTargetTemperature();
        AutoEjectButton.OnPressed += _ => OnToggleAutoEjectPressed?.Invoke();
        EnabledButton.OnPressed += _ => OnToggleEnabledPressed?.Invoke();
        EjectButton.OnPressed += _ => OnEjectPressed?.Invoke();
        // open-space edit end
    }

    public void UpdateState(SolutionHeaterBoundUserInterfaceState state)
    {
        // open-space edit start
        if (!TargetTemperatureLine.HasKeyboardFocus())
            TargetTemperatureLine.Text = $"{MathF.Round(state.TargetTemperature):F0}";

        CurrentTemperatureLabel.Text = float.IsNaN(state.CurrentTemperature)
            ? Loc.GetString("solution-heater-window-no-temperature-text")
            : Loc.GetString("solution-heater-window-temperature-value", ("temperature", MathF.Round(state.CurrentTemperature)));

        AutoEjectButton.Text = state.AutoEject
            ? Loc.GetString("solution-heater-window-auto-eject-on")
            : Loc.GetString("solution-heater-window-auto-eject-off");

        EnabledButton.Text = state.Enabled
            ? Loc.GetString("solution-heater-window-enabled-on")
            : Loc.GetString("solution-heater-window-enabled-off");

        UpdateContainerInfo(state.ContainerInfo);
        EjectButton.Disabled = state.ContainerInfo is null;
        // open-space edit end
    }

    private void UpdateContainerInfo(ContainerInfo? info)
    {
        ContainerInfo.Children.Clear();

        // open-space edit start
        if (info is null)
        {
            ContainerVolumeLabel.Text = string.Empty;
            ContainerInfo.Children.Add(new Label
            {
                Text = Loc.GetString("solution-heater-window-no-container-text")
            });
            return;
        }

        ContainerVolumeLabel.Text = Loc.GetString(
            "solution-heater-window-container-volume",
            ("current", info.CurrentVolume),
            ("max", info.MaxVolume));

        if (info.Reagents == null || info.Reagents.Count == 0)
        {
            ContainerInfo.Children.Add(new Label
            {
                Text = Loc.GetString("solution-heater-window-empty-container-text")
            });
            return;
        }

        foreach (var (reagentId, quantity) in info.Reagents)
        {
            var reagentName = _prototypeManager.TryIndex(reagentId.Prototype, out ReagentPrototype? proto)
                ? proto.LocalizedName
                : reagentId.Prototype;

            ContainerInfo.Children.Add(new Label
            {
                Text = Loc.GetString(
                    "solution-heater-window-container-reagent",
                    ("quantity", quantity),
                    ("reagent", reagentName))
            });
        }
        // open-space edit end
    }

    private void SubmitTargetTemperature()
    {
        // open-space edit start
        if (!float.TryParse(TargetTemperatureLine.Text, out var value))
            return;

        OnTargetTemperatureChanged?.Invoke(value);
        // open-space edit end
    }
}
