using System.Linq;
using System.Numerics;
using Content.Client.Roles;
using Content.Shared._OpenSpace.Administration;
using Content.Shared.Administration;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._OpenSpace.Administration.UI.TimeTransfer;

[GenerateTypedNameReferences]
public sealed partial class TimeTransferPanelWindow : DefaultWindow
{
    private const string OverallTracker = "Overall";
    private const int MaxMinutes = TimeTransferPanelEuiMsg.MaxMinutes;

    [Dependency] private readonly IEntityManager _entities = default!;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    private readonly JobSystem _jobs;
    private readonly List<RoleChoice> _roles = new();
    private readonly List<DepartmentChoice> _departments = new();
    private readonly HashSet<string> _selectedRoles = new(StringComparer.Ordinal);
    private readonly HashSet<string> _selectedDepartments = new(StringComparer.Ordinal);
    private readonly HashSet<string> _visibleRoles = new(StringComparer.Ordinal);
    private readonly HashSet<string> _visibleDepartments = new(StringComparer.Ordinal);
    private readonly Dictionary<string, int> _roleMinutes = new(StringComparer.Ordinal);
    private readonly HashSet<string> _customRoleMinutes = new(StringComparer.Ordinal);

    public event Action<string, TimeTransferPanelEntry[]>? AddTimeRequested;

    public TimeTransferPanelWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _jobs = _entities.System<JobSystem>();

        MinSize = new Vector2(760, 520);
        ModeTabs.SetTabTitle(0, Loc.GetString("time-transfer-panel-tab-roles"));
        ModeTabs.SetTabTitle(1, Loc.GetString("time-transfer-panel-tab-departments"));

        MinutesSpinBox.IsValid = value => value is > 0 and <= MaxMinutes;
        MinutesSpinBox.LineEditControl.MinSize = new Vector2(180, 0);
        MinutesSpinBox.Value = 60;
        MinutesSpinBox.ValueChanged += _ => OnDefaultMinutesChanged();

        PlayerList.OnSelectionChanged += OnPlayerSelected;
        RoleSearch.OnTextChanged += _ => RebuildRoles();
        DepartmentSearch.OnTextChanged += _ => RebuildDepartments();
        OverallCheckBox.OnToggled += _ => UpdateSummary();
        GroupButton.OnPressed += _ => RebuildRoles();
        SelectAllButton.OnPressed += _ => SelectVisible();
        ClearButton.OnPressed += _ => ClearCurrentSelection();
        AddButton.OnPressed += _ => Submit();
        DismissButton.OnPressed += _ => Close();
        ModeTabs.OnTabChanged += _ => UpdateSummary();

        PopulateChoices();
        RebuildRoles();
        RebuildDepartments();
        SetLocalStatus(Loc.GetString("time-transfer-panel-status-ready"), TimeTransferPanelStatusKind.Info);
    }

    public void ApplyState(TimeTransferPanelEuiState state)
    {
        AddButton.Disabled = !state.HasAccess;

        if (!state.HasAccess)
        {
            SetLocalStatus(Loc.GetString("time-transfer-panel-error-no-access"), TimeTransferPanelStatusKind.Error);
            return;
        }

        if (!string.IsNullOrWhiteSpace(state.Status))
            SetLocalStatus(state.Status, state.StatusKind);
        else
            SetLocalStatus(Loc.GetString("time-transfer-panel-status-ready"), TimeTransferPanelStatusKind.Info);
    }

    private void PopulateChoices()
    {
        var jobs = _prototypes.EnumeratePrototypes<JobPrototype>()
            .Where(job => !string.IsNullOrWhiteSpace(job.PlayTimeTracker))
            .ToList();
        jobs.Sort(JobUIComparer.Instance);

        foreach (var job in jobs)
        {
            var departmentId = string.Empty;
            var departmentName = Loc.GetString("time-transfer-panel-ungrouped");
            var departmentColor = Color.Gray;

            if (_jobs.TryGetPrimaryDepartment(job.ID, out var primaryDepartment) ||
                _jobs.TryGetDepartment(job.ID, out primaryDepartment))
            {
                departmentId = primaryDepartment.ID;
                departmentName = Loc.GetString(primaryDepartment.Name);
                departmentColor = primaryDepartment.Color;
            }

            _roles.Add(new RoleChoice(
                job.ID,
                job.PlayTimeTracker,
                job.LocalizedName,
                departmentId,
                departmentName,
                departmentColor));
        }

        var departments = _prototypes.EnumeratePrototypes<DepartmentPrototype>().ToList();
        departments.Sort(DepartmentUIComparer.Instance);

        foreach (var department in departments)
        {
            var trackers = new HashSet<string>(StringComparer.Ordinal);

            foreach (var role in department.Roles)
            {
                if (_prototypes.TryIndex<JobPrototype>(role, out var job) &&
                    !string.IsNullOrWhiteSpace(job.PlayTimeTracker))
                {
                    trackers.Add(job.PlayTimeTracker);
                }
            }

            if (trackers.Count == 0)
                continue;

            _departments.Add(new DepartmentChoice(
                department.ID,
                Loc.GetString(department.Name),
                department.Color,
                trackers.ToArray()));
        }
    }

    private void RebuildRoles()
    {
        _visibleRoles.Clear();
        RolesContainer.RemoveAllChildren();

        var visible = _roles
            .Where(role => MatchesRole(role, RoleSearch.Text))
            .ToList();

        if (GroupButton.Pressed)
        {
            foreach (var group in visible.GroupBy(role => role.DepartmentName))
            {
                AddHeader(RolesContainer, group.Key, group.First().DepartmentColor);

                foreach (var role in group)
                    AddRoleRow(role);
            }
        }
        else
        {
            foreach (var role in visible)
                AddRoleRow(role);
        }

        UpdateSummary();
    }

    private void RebuildDepartments()
    {
        _visibleDepartments.Clear();
        DepartmentsContainer.RemoveAllChildren();

        foreach (var department in _departments.Where(department => MatchesDepartment(department, DepartmentSearch.Text)))
        {
            _visibleDepartments.Add(department.Id);

            var checkBox = new CheckBox
            {
                Text = Loc.GetString(
                    "time-transfer-panel-department-entry",
                    ("department", department.Name),
                    ("count", department.Trackers.Length)),
                HorizontalExpand = true,
                Pressed = _selectedDepartments.Contains(department.Id),
                ToolTip = string.Join(", ", department.Trackers),
            };
            checkBox.Label.FontColorOverride = department.Color;

            checkBox.OnToggled += args =>
            {
                if (args.Pressed)
                    _selectedDepartments.Add(department.Id);
                else
                    _selectedDepartments.Remove(department.Id);

                UpdateSummary();
            };

            DepartmentsContainer.AddChild(checkBox);
        }

        UpdateSummary();
    }

    private void AddRoleRow(RoleChoice role)
    {
        _visibleRoles.Add(role.Tracker);
        var selected = _selectedRoles.Contains(role.Tracker);
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 1),
        };

        var checkBox = new CheckBox
        {
            Text = Loc.GetString(
                "time-transfer-panel-role-entry",
                ("role", role.Name),
                ("id", role.JobId)),
            HorizontalExpand = true,
            Pressed = selected,
            ToolTip = Loc.GetString(
                "time-transfer-panel-role-tooltip",
                ("tracker", role.Tracker),
                ("department", role.DepartmentName)),
        };

        var minutes = CreateRoleMinutesSpinBox(role.Tracker, selected);

        checkBox.OnToggled += args =>
        {
            if (args.Pressed)
            {
                SelectRole(role.Tracker);
            }
            else
            {
                _selectedRoles.Remove(role.Tracker);
                if (!_customRoleMinutes.Contains(role.Tracker))
                    _roleMinutes.Remove(role.Tracker);
            }

            minutes.LineEditDisabled = !args.Pressed;
            UpdateSummary();
        };

        row.AddChild(checkBox);
        row.AddChild(minutes);
        RolesContainer.AddChild(row);
    }

    private SpinBox CreateRoleMinutesSpinBox(string tracker, bool enabled)
    {
        var minutes = new SpinBox
        {
            MinWidth = 120,
            IsValid = value => value is > 0 and <= MaxMinutes,
        };
        minutes.LineEditControl.MinSize = new Vector2(100, 0);
        minutes.LineEditDisabled = !enabled;
        minutes.Value = GetRoleMinutes(tracker);
        minutes.ValueChanged += args =>
        {
            _roleMinutes[tracker] = args.Value;
            _customRoleMinutes.Add(tracker);
            UpdateSummary();
        };

        return minutes;
    }

    private static void AddHeader(BoxContainer container, string text, Color color)
    {
        container.AddChild(new Label
        {
            Text = text,
            FontColorOverride = color,
            Margin = new Thickness(0, 6, 0, 2),
        });
    }

    private void SelectVisible()
    {
        if (ModeTabs.CurrentTab == 0)
        {
            foreach (var tracker in _visibleRoles)
            {
                SelectRole(tracker);
            }

            RebuildRoles();
        }
        else
        {
            _selectedDepartments.UnionWith(_visibleDepartments);
            RebuildDepartments();
        }
    }

    private void ClearCurrentSelection()
    {
        if (ModeTabs.CurrentTab == 0)
        {
            _selectedRoles.Clear();
            _roleMinutes.Clear();
            _customRoleMinutes.Clear();
            RebuildRoles();
        }
        else
        {
            _selectedDepartments.Clear();
            RebuildDepartments();
        }
    }

    private void Submit()
    {
        var player = PlayerLine.Text.Trim();
        if (string.IsNullOrWhiteSpace(player))
        {
            SetLocalStatus(Loc.GetString("time-transfer-panel-error-no-player"), TimeTransferPanelStatusKind.Error);
            return;
        }

        var entries = GetCurrentEntries();
        if (entries.Length == 0)
        {
            SetLocalStatus(Loc.GetString("time-transfer-panel-error-no-roles"), TimeTransferPanelStatusKind.Error);
            return;
        }

        if (MinutesSpinBox.Value <= 0)
        {
            SetLocalStatus(Loc.GetString("time-transfer-panel-error-no-minutes"), TimeTransferPanelStatusKind.Error);
            return;
        }

        AddTimeRequested?.Invoke(player, entries);
        SetLocalStatus(Loc.GetString("time-transfer-panel-status-applying"), TimeTransferPanelStatusKind.Info);
    }

    private TimeTransferPanelEntry[] GetCurrentEntries()
    {
        var entries = new Dictionary<string, int>(StringComparer.Ordinal);

        if (OverallCheckBox.Pressed)
            entries[OverallTracker] = MinutesSpinBox.Value;

        if (ModeTabs.CurrentTab == 0)
        {
            foreach (var tracker in _selectedRoles)
            {
                entries[tracker] = GetRoleMinutes(tracker);
            }
        }
        else
        {
            foreach (var tracker in GetCurrentTrackers())
            {
                entries[tracker] = MinutesSpinBox.Value;
            }
        }

        var result = new TimeTransferPanelEntry[entries.Count];
        var index = 0;

        foreach (var entry in entries)
        {
            result[index] = new TimeTransferPanelEntry(entry.Key, entry.Value);
            index++;
        }

        return result;
    }

    private string[] GetCurrentTrackers()
    {
        if (ModeTabs.CurrentTab == 0)
            return _selectedRoles.ToArray();

        var trackers = new HashSet<string>(StringComparer.Ordinal);
        foreach (var department in _departments)
        {
            if (!_selectedDepartments.Contains(department.Id))
                continue;

            trackers.UnionWith(department.Trackers);
        }

        return trackers.ToArray();
    }

    private void UpdateSummary()
    {
        var entries = GetCurrentEntries();
        var totalMinutes = 0;
        foreach (var entry in entries)
        {
            totalMinutes += entry.Minutes;
        }

        var overallStatus = Loc.GetString(OverallCheckBox.Pressed
            ? "time-transfer-panel-overall-included"
            : "time-transfer-panel-overall-skipped");

        if (ModeTabs.CurrentTab == 0)
        {
            SummaryLabel.Text = Loc.GetString(
                "time-transfer-panel-summary-roles",
                ("count", _selectedRoles.Count),
                ("minutes", totalMinutes),
                ("overall", overallStatus));
            return;
        }

        SummaryLabel.Text = Loc.GetString(
            "time-transfer-panel-summary-departments",
            ("departments", _selectedDepartments.Count),
            ("roles", GetCurrentTrackers().Length),
            ("minutes", totalMinutes),
            ("overall", overallStatus));
    }

    private void SelectRole(string tracker)
    {
        _selectedRoles.Add(tracker);

        if (!_roleMinutes.ContainsKey(tracker))
            _roleMinutes[tracker] = MinutesSpinBox.Value;
    }

    private int GetRoleMinutes(string tracker)
    {
        return _roleMinutes.TryGetValue(tracker, out var minutes)
            ? minutes
            : MinutesSpinBox.Value;
    }

    private void OnDefaultMinutesChanged()
    {
        foreach (var tracker in _selectedRoles)
        {
            if (_customRoleMinutes.Contains(tracker))
                continue;

            _roleMinutes[tracker] = MinutesSpinBox.Value;
        }

        RebuildRoles();
        UpdateSummary();
    }

    private void SetLocalStatus(string text, TimeTransferPanelStatusKind kind)
    {
        StatusLabel.Text = text;
        StatusLabel.FontColorOverride = kind switch
        {
            TimeTransferPanelStatusKind.Success => Color.LightGreen,
            TimeTransferPanelStatusKind.Error => Color.Red,
            TimeTransferPanelStatusKind.Info => Color.Gold,
            _ => Color.Gray,
        };
    }

    private void OnPlayerSelected(PlayerInfo? player)
    {
        if (player != null)
            PlayerLine.Text = player.Username;
    }

    private static bool MatchesRole(RoleChoice role, string filter)
    {
        return string.IsNullOrWhiteSpace(filter) ||
               role.Name.Contains(filter, StringComparison.OrdinalIgnoreCase) ||
               role.JobId.Contains(filter, StringComparison.OrdinalIgnoreCase) ||
               role.Tracker.Contains(filter, StringComparison.OrdinalIgnoreCase) ||
               role.DepartmentName.Contains(filter, StringComparison.OrdinalIgnoreCase);
    }

    private static bool MatchesDepartment(DepartmentChoice department, string filter)
    {
        return string.IsNullOrWhiteSpace(filter) ||
               department.Name.Contains(filter, StringComparison.OrdinalIgnoreCase) ||
               department.Id.Contains(filter, StringComparison.OrdinalIgnoreCase);
    }

    private sealed record RoleChoice(
        string JobId,
        string Tracker,
        string Name,
        string DepartmentId,
        string DepartmentName,
        Color DepartmentColor);

    private sealed record DepartmentChoice(
        string Id,
        string Name,
        Color Color,
        string[] Trackers);
}
