name: Сообщить о баге
description: Сообщите о баге разработчикам да бы они могли его решить.
body:
  - type: markdown
    attributes:
      value: |
       Спасибо, что уделили время заполнению формы. Для обратной связи или помощи в работе с нашим сервером всегда доступен наш [Дискорд](https://discord.gg/Tnj2gX92Bg).
  - type: input
    attributes:
      label: На какой версии билда был найден баг?
      description: Версию найти вы можете в игре, открыв Обновления, где левом-нижнем углу окна указана версия.
      placeholder: ss14-art/gqxgji1
    validations:
      required: false
  - type: textarea
    attributes:
      label: Описание
      description: |
        Чёткое и краткое описание проблемы.
        Если проблема носит визуальный характер, рекомендуется разместить скриншот.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Как повторить баг?
      description: Подробно по шагам распишите как повторить баг.
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Дополнительный контекст
      description: Добавьте ещё какой либо дополнительный контекст о найденом вами баге.
    validations:
      required: false

