name: Сообщите о проблеме с картой
description: Сообщите о проблеме с картой, связанные с ошибками, недопустимыми действиями или другими проблемами, которые вы заметили на карте.
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что уделили время заполнению формы. Для обратной связи или помощи в работе с нашим сервером всегда доступен наш [Дискорд](https://discord.gg/Tnj2gX92Bg).
  - type: input
    attributes:
      label: На какой версии билда была найдена проблема?
      description: Версию найти вы можете в игре, открыв Обновления, где левом-нижнем углу окна указана версия.
      placeholder: ss14-art/gqxgji1
    validations:
      required: false
  - type: input
    attributes:
      label: На какой станции, в каком шаттле или на каком гриде возникла проблема?
      description: Название станции, шаттла или грида. Если вы не знаете названия, попробуйте описать его.
      placeholder: Box Station
    validations:
      required: true
  - type: textarea
    attributes:
      label: Описание
      description: |
        Чёткое и краткое описание проблемы.
        Если проблема носит визуальный характер, рекомендуется разместить скриншот.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Как повторить проблему?
      description: Подробно по шагам распишите как повторить проблему.
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Дополнительный контекст
      description: Добавьте ещё какой-либо дополнительный контекст о найденной проблеме.
    validations:
      required: false

