blank_issues_enabled: true
contact_links:
  - name: Запросить иное
    url: https://discord.gg/Tnj2gX92Bg
    about: Отправляйте запросы на добавление новых функций в наш Дискорд (https://discord.gg/Tnj2gX92Bg).
