using System.Numerics;
using Content.Shared.Atmos;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.HealthAnalyzer.UI;

// Health analyzer UI is split from its window because it's used by both the
// health analyzer item and the cryo pod UI.

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerControl : BoxContainer
{
    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;

    public HealthAnalyzerControl()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();
    }

    public void Populate(HealthAnalyzerUiState state)
    {
        var target = _entityManager.GetEntity(state.TargetEntity);

        NoPatientDataText.Visible = !state.HasData;
        PatientDataContainer.Visible = state.HasData;
        if (!state.HasData)
            return;

        ScanModeLabel.Text = state.ScanMode.HasValue
            ? state.ScanMode.Value
                ? Loc.GetString("health-analyzer-window-scan-mode-active")
                : Loc.GetString("health-analyzer-window-scan-mode-inactive")
            : Loc.GetString("health-analyzer-window-entity-unknown-text");
        ScanModeLabel.FontColorOverride = state.ScanMode == true ? Color.Green : Color.Red;

        SpriteView.Visible = target != null && state.ScanMode == true;
        NoDataTex.Visible = !SpriteView.Visible;
        if (target != null)
            SpriteView.SetEntity(target.Value);

        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(string.IsNullOrWhiteSpace(state.PatientName)
            ? Loc.GetString("health-analyzer-window-entity-unknown-text")
            : state.PatientName);
        NameLabel.SetMessage(name);

        SpeciesLabel.Text = !string.IsNullOrWhiteSpace(state.SpeciesName)
            ? state.SpeciesName
            : TryGetSpeciesName(target);

        ConditionLabel.Text = !float.IsNaN(state.Condition)
            ? Loc.GetString("health-analyzer-window-condition-value", ("condition", $"{state.Condition:F0}"))
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        StatusLabel.Text = state.MobState.HasValue
            ? GetStatus(state.MobState.Value)
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        TemperatureLabel.Text = !float.IsNaN(state.Temperature)
            ? FormatTemperature(state.Temperature)
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        BloodLabel.Text = !float.IsNaN(state.BloodLevel)
            ? Loc.GetString(
                "health-analyzer-window-blood-value",
                ("percent", $"{state.BloodLevel * 100f:F1}"),
                ("volume", state.BloodAmount))
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        PulseLabel.Text = state.Pulse.HasValue
            ? Loc.GetString("health-analyzer-window-pulse-value", ("pulse", state.Pulse.Value))
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        GenesLabel.Text = state.GenesStable switch
        {
            true => Loc.GetString("health-analyzer-window-genes-stable"),
            false => Loc.GetString("health-analyzer-window-genes-unstable"),
            _ => Loc.GetString("health-analyzer-window-entity-unknown-value-text"),
        };

        DamageTypesLabel.SetMessage(BuildDamageTypeMessage());
        DamageValuesLabel.Text = Loc.GetString(
            "health-analyzer-window-damage-values",
            ("airloss", state.AirlossDamage),
            ("toxin", state.ToxinDamage),
            ("burn", state.BurnDamage),
            ("brute", state.BruteDamage));

        PopulateReagents(state);
        PopulateDependencies(state);
        NotesLabel.Text = Loc.GetString("health-analyzer-window-notes-empty");
    }

    private void PopulateReagents(HealthAnalyzerUiState state)
    {
        ReagentsContainer.RemoveAllChildren();

        if (state.Reagents.Count == 0)
        {
            ReagentsContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-window-reagents-none"),
            });
            return;
        }

        foreach (var reagent in state.Reagents)
        {
            var localizedName = _prototypes.TryIndex<ReagentPrototype>(reagent.ReagentPrototype, out var proto)
                ? proto.LocalizedName
                : reagent.ReagentPrototype;

            ReagentsContainer.AddChild(new Label
            {
                Text = Loc.GetString(
                    "health-analyzer-window-reagent-entry",
                    ("quantity", reagent.Quantity),
                    ("reagent", localizedName)),
            });
        }
    }

    private void PopulateDependencies(HealthAnalyzerUiState state)
    {
        DependenciesContainer.RemoveAllChildren();

        if (state.Dependencies.Count == 0)
        {
            DependenciesContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-window-dependencies-none"),
            });
            return;
        }

        foreach (var dependency in state.Dependencies)
        {
            DependenciesContainer.AddChild(new Label
            {
                Text = dependency,
            });
        }
    }

    private string TryGetSpeciesName(EntityUid? target)
    {
        if (target != null &&
            _entityManager.TryGetComponent<HumanoidProfileComponent>(target.Value, out var humanoidComponent) &&
            _prototypes.TryIndex(humanoidComponent.Species, out SpeciesPrototype? species))
        {
            return Loc.GetString(species.Name);
        }

        return Loc.GetString("health-analyzer-window-entity-unknown-species-text");
    }

    private static string FormatTemperature(float temperature)
    {
        var celsius = temperature - Atmospherics.T0C;
        var fahrenheit = celsius * 9f / 5f + 32f;
        return Loc.GetString(
            "health-analyzer-window-temperature-value",
            ("tempC", $"{celsius:F2}"),
            ("tempF", $"{fahrenheit:F2}"));
    }

    private FormattedMessage BuildDamageTypeMessage()
    {
        var msg = new FormattedMessage();
        msg.PushColor(Color.Cyan);
        msg.AddText(Loc.GetString("health-analyzer-window-damage-airloss"));
        msg.Pop();
        msg.AddText(" / ");
        msg.PushColor(Color.Green);
        msg.AddText(Loc.GetString("health-analyzer-window-damage-toxin"));
        msg.Pop();
        msg.AddText(" / ");
        msg.PushColor(Color.Orange);
        msg.AddText(Loc.GetString("health-analyzer-window-damage-burn"));
        msg.Pop();
        msg.AddText(" / ");
        msg.PushColor(Color.Red);
        msg.AddText(Loc.GetString("health-analyzer-window-damage-brute"));
        msg.Pop();
        return msg;
    }

    private static string GetStatus(MobState mobState)
    {
        return mobState switch
        {
            MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
            MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
            MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
            _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
        };
    }
}
