- type: job
  id: BlueShield
  name: job-name-blueshield
  description: job-description-blueshield
  playTimeTracker: JobBlueShield
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hrs
    - !type:DepartmentTimeRequirement
      department: Command
      time: 72000 # 20 hrs
  startingGear: BlueShieldGear
  icon: JobIconBlueShield
  rules: job-rules-corporate-aligned
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Command
    - Bar
    - Service
    - Maintenance
    - Janitor
    - Theatre
    - Kitchen
    - Chapel
    - Hydroponics
    - External
    - Chemistry
    - Engineering
    - Research
    - Robotics
    - Detective
    - Salvage
    - Security
    - Brigmedic
    - Brig
    - Lawyer
    - Cargo
    - Atmospherics
    - Cargo
    - Medical
    - BlueShield
    - Surgery
    - Paramedic
    - Mining
    - SalvageLead
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]

- type: startingGear
  id: BlueShieldGear
  equipment:
    # head: ClothingHeadHatBeretBlueShield
    # id: BlueShieldPDA
    ears: ClothingHeadsetAltBSO # Starlight
    # belt: ClothingBeltBlueShieldWebbingFilled
    gloves: ClothingHandsGlovesCombat
    # pocket1: WeaponMultiphaseGun
    pocket1: WeaponAdvancedLaserBSO
    pocket2: HandheldCrewMonitor # open space-edit
  storage:
    back:
    - Flash
    - ClothingMaskGasBSO

- type: chameleonOutfit
  id: BlueShieldChameleonOutfit
  job: BlueShield
  equipment:
    head: ClothingHeadHatBeretBlueShield
    gloves: ClothingHandsGlovesCombat

# open space-edit start
# TODO: переделать это в нормальную пушку для синего щита
- type: entity
  id: WeaponAdvancedLaserBSO
  name: BlueShield laser pistol
  parent: [BaseWeaponBatterySmall, BaseSecurityContraband]
  description: A standard-issue laser pistol for BlueShield officers. Reliable energy sidearm for protecting command staff.
  components:
  - type: Item
    size: Small
    shape:
    - 0,0,1,1
  - type: Sprite
    sprite: Objects/Weapons/Guns/Battery/advancedlasergun.rsi
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-unshaded-4
      map: ["enum.GunVisualLayers.MagUnshaded"]
      shader: unshaded
  - type: Clothing
    sprite: Objects/Weapons/Guns/Battery/advancedlasergun.rsi
  - type: Gun
    soundGunshot:
      path: /Audio/Weapons/Guns/Gunshots/laser_cannon.ogg
  - type: BatteryAmmoProvider
    proto: RedMediumLaser
    fireCost: 100
  - type: MagazineVisuals
    magState: mag
    steps: 5
    zeroVisible: true
  - type: Appearance
  - type: StaticPrice
    price: 63
  - type: Tag
    tags:
    - Sidearm
    - LaserWeapon
# open space-edit stop
