using System.Globalization;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._OpenSpace.Administration.UI.PlayTimePanel;

/// <summary>
/// Window for the "Time Transfer" admin panel. Displays every play-time
/// tracker and every department and lets the admin add time to a single
/// row, or to every selected row at once via the "group" button. Time is
/// always entered in minutes.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PlayTimePanel : FancyWindow
{
    private const int TabRoles = 0;
    private const int TabDepartments = 1;

    /// <summary>Raised when the admin asks to look up a new target player.</summary>
    public event Action<string>? LookupPlayerRequested;

    /// <summary>Raised when the admin asks to re-sync the panel state.</summary>
    public event Action? RefreshRequested;

    /// <summary>
    /// Raised when the admin applies play-time changes. The dictionary maps
    /// tracker IDs to minutes (may be negative). <c>overallMinutes</c> is the
    /// amount applied to the overall playtime counter.
    /// </summary>
    public event Action<Dictionary<string, int>, int>? AddTimeRequested;

    private readonly List<RoleRow> _roleRows = new();
    private readonly List<DepartmentRow> _departmentRows = new();

    public PlayTimePanel()
    {
        RobustXamlLoader.Load(this);

        Tabs.SetTabTitle(TabRoles, Loc.GetString("playtime-panel-tab-roles"));
        Tabs.SetTabTitle(TabDepartments, Loc.GetString("playtime-panel-tab-departments"));

        LookupButton.OnPressed += _ => LookupPlayerRequested?.Invoke(PlayerNameInput.Text ?? string.Empty);
        PlayerNameInput.OnTextEntered += args => LookupPlayerRequested?.Invoke(args.Text);
        RefreshButton.OnPressed += _ => RefreshRequested?.Invoke();

        GroupApplyButton.OnPressed += _ => OnGroupApply();
        SelectAllButton.OnPressed += _ => SetAllSelection(true);
        SelectNoneButton.OnPressed += _ => SetAllSelection(false);

        OverallAddButton.OnPressed += _ => OnOverallAdd();
    }

    public void UpdateState(PlayTimePanelEuiState state)
    {
        if (PlayerNameInput.Text != state.PlayerName)
            PlayerNameInput.Text = state.PlayerName;

        if (!string.IsNullOrEmpty(state.StatusMessage))
        {
            StatusLabel.Text = state.StatusMessage;
        }
        else if (string.IsNullOrWhiteSpace(state.PlayerName))
        {
            StatusLabel.Text = Loc.GetString("playtime-panel-status-empty");
        }
        else if (!state.PlayerFound)
        {
            StatusLabel.Text = Loc.GetString("playtime-panel-status-not-online", ("player", state.PlayerName));
        }
        else
        {
            StatusLabel.Text = Loc.GetString("playtime-panel-status-found", ("player", state.PlayerName));
        }

        OverallLabel.Text = Loc.GetString(
            "playtime-panel-overall",
            ("hours", (int) state.OverallPlaytime.TotalHours),
            ("minutes", state.OverallPlaytime.Minutes));

        var activeTab = Tabs.CurrentTab;
        var lookup = BuildLookup();

        RebuildRoles(state.Roles, lookup);
        RebuildDepartments(state.Departments, lookup);

        Tabs.CurrentTab = activeTab;
    }

    private Dictionary<string, RowState> BuildLookup()
    {
        // Preserve checkbox state and per-row minutes across refreshes so
        // a state update in the middle of editing doesn't reset the UI.
        var lookup = new Dictionary<string, RowState>(StringComparer.OrdinalIgnoreCase);
        foreach (var row in _roleRows)
        {
            lookup["role:" + row.TrackerId] = new RowState(row.Selected, row.MinutesText);
        }
        foreach (var row in _departmentRows)
        {
            lookup["dept:" + row.DepartmentId] = new RowState(row.Selected, row.MinutesText);
        }
        return lookup;
    }

    private void RebuildRoles(List<PlayTimeRoleEntry> roles, Dictionary<string, RowState> lookup)
    {
        RolesContainer.RemoveAllChildren();
        _roleRows.Clear();

        foreach (var role in roles)
        {
            var row = new RoleRow(role);
            if (lookup.TryGetValue("role:" + role.TrackerId, out var saved))
            {
                row.Selected = saved.Selected;
                row.MinutesText = saved.Minutes;
            }

            row.AddPressed += minutes => ApplySingleTracker(role.TrackerId, minutes);

            _roleRows.Add(row);
            RolesContainer.AddChild(row);
        }

        if (roles.Count == 0)
            RolesContainer.AddChild(new Label { Text = Loc.GetString("playtime-panel-empty-list"), Margin = new(4) });
    }

    private void RebuildDepartments(List<PlayTimeDepartmentEntry> departments, Dictionary<string, RowState> lookup)
    {
        DepartmentsContainer.RemoveAllChildren();
        _departmentRows.Clear();

        foreach (var department in departments)
        {
            var row = new DepartmentRow(department);
            if (lookup.TryGetValue("dept:" + department.DepartmentId, out var saved))
            {
                row.Selected = saved.Selected;
                row.MinutesText = saved.Minutes;
            }

            row.AddPressed += minutes => ApplyDepartment(department, minutes);

            _departmentRows.Add(row);
            DepartmentsContainer.AddChild(row);
        }

        if (departments.Count == 0)
            DepartmentsContainer.AddChild(new Label { Text = Loc.GetString("playtime-panel-empty-list"), Margin = new(4) });
    }

    private void SetAllSelection(bool selected)
    {
        if (Tabs.CurrentTab == TabRoles)
        {
            foreach (var row in _roleRows)
                row.Selected = selected;
        }
        else
        {
            foreach (var row in _departmentRows)
                row.Selected = selected;
        }
    }

    private void OnGroupApply()
    {
        if (!TryParseMinutes(GroupMinutesInput.Text, out var minutes) || minutes == 0)
        {
            StatusLabel.Text = Loc.GetString("playtime-panel-status-invalid-minutes");
            return;
        }

        var trackers = new Dictionary<string, int>();
        if (Tabs.CurrentTab == TabRoles)
        {
            foreach (var row in _roleRows.Where(r => r.Selected))
                trackers[row.TrackerId] = minutes;
        }
        else
        {
            foreach (var row in _departmentRows.Where(r => r.Selected))
            {
                foreach (var trackerId in row.Trackers)
                    trackers[trackerId] = minutes;
            }
        }

        if (trackers.Count == 0)
        {
            StatusLabel.Text = Loc.GetString("playtime-panel-status-no-selection");
            return;
        }

        AddTimeRequested?.Invoke(trackers, 0);
    }

    private void ApplySingleTracker(string trackerId, int minutes)
    {
        var trackers = new Dictionary<string, int> { [trackerId] = minutes };
        AddTimeRequested?.Invoke(trackers, 0);
    }

    private void ApplyDepartment(PlayTimeDepartmentEntry department, int minutes)
    {
        var trackers = new Dictionary<string, int>();
        foreach (var trackerId in department.Trackers)
            trackers[trackerId] = minutes;

        if (trackers.Count == 0)
        {
            StatusLabel.Text = Loc.GetString("playtime-panel-status-empty-department");
            return;
        }

        AddTimeRequested?.Invoke(trackers, 0);
    }

    private void OnOverallAdd()
    {
        if (!TryParseMinutes(OverallMinutesInput.Text, out var minutes) || minutes == 0)
        {
            StatusLabel.Text = Loc.GetString("playtime-panel-status-invalid-minutes");
            return;
        }

        AddTimeRequested?.Invoke(new Dictionary<string, int>(), minutes);
    }

    private static bool TryParseMinutes(string? text, out int minutes)
    {
        if (int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out minutes))
            return true;

        minutes = 0;
        return false;
    }

    private readonly record struct RowState(bool Selected, string Minutes);

    /// <summary>Row used on the "By Roles" tab.</summary>
    private sealed class RoleRow : BoxContainer
    {
        public readonly string TrackerId;

        public event Action<int>? AddPressed;

        private readonly CheckBox _checkBox;
        private readonly LineEdit _minutesInput;

        public bool Selected
        {
            get => _checkBox.Pressed;
            set => _checkBox.Pressed = value;
        }

        public string MinutesText
        {
            get => _minutesInput.Text ?? string.Empty;
            set => _minutesInput.Text = value;
        }

        public RoleRow(PlayTimeRoleEntry entry)
        {
            TrackerId = entry.TrackerId;
            Orientation = LayoutOrientation.Horizontal;
            Margin = new Thickness(4, 2);
            HorizontalExpand = true;

            _checkBox = new CheckBox
            {
                MinSize = new(24, 24),
                VerticalAlignment = VAlignment.Center,
            };
            AddChild(_checkBox);

            AddChild(new Control { MinSize = new(4, 0) });

            AddChild(new Label
            {
                Text = entry.DisplayName,
                MinWidth = 180,
                VerticalAlignment = VAlignment.Center,
            });

            AddChild(new Label
            {
                Text = Loc.GetString(
                    "playtime-panel-row-current",
                    ("hours", (int) entry.CurrentTime.TotalHours),
                    ("minutes", entry.CurrentTime.Minutes)),
                MinWidth = 120,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            });

            _minutesInput = new LineEdit
            {
                PlaceHolder = "0",
                MinWidth = 70,
                VerticalAlignment = VAlignment.Center,
            };
            AddChild(_minutesInput);

            AddChild(new Control { MinSize = new(4, 0) });

            var addButton = new Button
            {
                Text = Loc.GetString("playtime-panel-add"),
                VerticalAlignment = VAlignment.Center,
            };
            addButton.OnPressed += _ =>
            {
                if (TryParseMinutes(_minutesInput.Text, out var minutes) && minutes != 0)
                    AddPressed?.Invoke(minutes);
            };
            AddChild(addButton);
        }
    }

    /// <summary>Row used on the "By Departments" tab.</summary>
    private sealed class DepartmentRow : BoxContainer
    {
        public readonly string DepartmentId;
        public readonly List<string> Trackers;

        public event Action<int>? AddPressed;

        private readonly CheckBox _checkBox;
        private readonly LineEdit _minutesInput;

        public bool Selected
        {
            get => _checkBox.Pressed;
            set => _checkBox.Pressed = value;
        }

        public string MinutesText
        {
            get => _minutesInput.Text ?? string.Empty;
            set => _minutesInput.Text = value;
        }

        public DepartmentRow(PlayTimeDepartmentEntry entry)
        {
            DepartmentId = entry.DepartmentId;
            Trackers = entry.Trackers;
            Orientation = LayoutOrientation.Horizontal;
            Margin = new Thickness(4, 2);
            HorizontalExpand = true;

            _checkBox = new CheckBox
            {
                MinSize = new(24, 24),
                VerticalAlignment = VAlignment.Center,
            };
            AddChild(_checkBox);

            AddChild(new Control { MinSize = new(4, 0) });

            var nameLabel = new Label
            {
                Text = Loc.GetString(entry.DisplayName),
                MinWidth = 180,
                VerticalAlignment = VAlignment.Center,
                FontColorOverride = entry.Color,
            };
            AddChild(nameLabel);

            AddChild(new Label
            {
                Text = Loc.GetString("playtime-panel-dept-trackers", ("count", entry.Trackers.Count)),
                MinWidth = 120,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            });

            _minutesInput = new LineEdit
            {
                PlaceHolder = "0",
                MinWidth = 70,
                VerticalAlignment = VAlignment.Center,
            };
            AddChild(_minutesInput);

            AddChild(new Control { MinSize = new(4, 0) });

            var addButton = new Button
            {
                Text = Loc.GetString("playtime-panel-add"),
                VerticalAlignment = VAlignment.Center,
            };
            addButton.OnPressed += _ =>
            {
                if (TryParseMinutes(_minutesInput.Text, out var minutes) && minutes != 0)
                    AddPressed?.Invoke(minutes);
            };
            AddChild(addButton);
        }
    }
}
